### ISSUE TITLE
требую версию для линукса!

### ISSUE THREAD

**Issue by dentlis** [Vermilonik/TelegramBackdoor#1]

**Comment by Vermilonik** [comment]
дело в том, если компилировать этот код в линуксе, тогда в конце выйдет не .ехе файл(лично так работает pyinstaller). если знаешь какую-то библиотеку по компиляции(кроме pyinstaller), тогда напиши её название, пожалуйста

**Comment by dentlis** [comment]
пишу бєкдор для линукса
